# ** SKELETON CONFIGUREATION FILE FOR APODWall 
# ** Leave the custom section blank if not using custom options.
# NOTE: PATHS ARE RELATIVE TO WHERE CONFIG.PY AND APODWALL.PY ARE LOCATED.
#       USE A SLASH TO USE AN ABSOLUTE PATH.
# IMAGE_DIR - Location to save all image types besides thumbnails.
# TIMG_DIR - Location to save thumbnails.
# DATA_FILE - Location the data file saves to.
# ORIG_SAVE - Amount of original unaltered images to keep saved.
# TIMG_SAVE - Amount of thumbnails to keep saved. Thumbnail logs have all of the apod data attached.
# CROP_SAVE - Amount of cropped images to keep saved.
# TMP_SAVE Amount of tmp images saved. Images that are below MIN_SIZE.
# QUALITY - Image quality, "hd" or "standard".
# MIN_SIZE - Minimum width x height images to set as wallpaper. Ex: "1000x600"
# CROP_RATIO - Aspect ratio to crop images. Ex: "16:9".
# API_KEY - API key for apod.nasa.gov, register for one at https://api.nasa.gov.
# CUSTOM_CMD - Custom command to use to set wallpaper. Use "{}" where the image path should be. Ex: "wallpaper-command {} mode=stretch".
# CUSTOM_ENV - Custom environment variable to use. Defaults to XDG_CURRENT_DESKTOP.

title = "User_Settings"

[GENERAL]
IMAGE_DIR = "path/wallpapers"
TIMG_DIR = "path/wallpapers/thumbnails"
DATA_FILE = "path/data/file"
ORIG_SAVE = 10
TIMG_SAVE = 100
CROP_SAVE = 1
TMP_SAVE = 0

[IMAGE]
QUALITY = "hd"
MIN_SIZE = "1000x600"
CROP_RATIO = "16:9"

[API]
API_KEY = "apikeygoeshere"

[CUSTOM]
CUSTOM_CMD = ""
CUSTOM_ENV = "XDG_CURRENT_DESKTOP"
